export enum SortingOptions {
  NAME_ASC = 'NAME_ASC',
  NAME_DESC = 'NAME_DESC',
  HEIGHT_ASC = 'HEIGHT_ASC',
  HEIGHT_DESC = 'HEIGHT_DESC',
  WEIGHT_ASC = 'WEIGHT_ASC',
  WEIGHT_DESC = 'WEIGHT_DESC',
  DATE_ASC = 'DATE_ASC',
  DATE_DESC = 'DATE_DESC'
}
